import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { type Metadata } from 'next';
import {
  Geist_Mono as geistFontMono,
  Geist as geistFontSans,
} from 'next/font/google';
import './globals.css';

const geistSans = geistFontSans({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = geistFontMono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
};

export default RootLayout;
