name: Pre install dependencies

inputs:
  PLATFORM:
    description: 'android | ios | js'
    required: true
    default: 'js'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10.19.0
        run_install: false

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts

    - name: Install ruby dependencies
      if: ${{ inputs.PLATFORM == 'android' || inputs.PLATFORM == 'ios' }}
      uses: ruby/setup-ruby@v1
      with:
        working-directory: apps/mobile
        ruby-version: '3.3'
        bundler-cache: true
        cache-version: 2

    - name: Install android dependencies
      if: ${{ inputs.PLATFORM == 'android' }}
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
        cache: 'gradle'

    - name: Setup Gradle cache
      if: ${{ inputs.PLATFORM == 'android' }}
      uses: gradle/actions/setup-gradle@v4

    - name: Setup Xcode
      if: ${{ inputs.PLATFORM == 'ios' }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.4

    - name: Export Xcode version
      if: ${{ inputs.PLATFORM == 'ios' }}
      shell: bash
      run: echo "XCODE_VERSION=$(xcodebuild -version | head -n1 | awk '{print $2}')" >> $GITHUB_ENV

    - name: Restore CocoaPods cache
      if: ${{ inputs.PLATFORM == 'ios' }}
      uses: actions/cache@v4
      with:
        path: |
          apps/mobile/ios/Pods
          $HOME/.cocoapods
          $HOME/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-xcode-${{ env.XCODE_VERSION }}-${{ hashFiles('apps/mobile/ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-xcode-${{ env.XCODE_VERSION }}-

    - name: Install CocoaPods
      if: ${{ inputs.PLATFORM == 'ios' }}
      shell: bash
      run: cd apps/mobile/ios && bundle exec pod install && cd ..

    - name: Restore DerivedData cache
      if: ${{ inputs.PLATFORM == 'ios' }}
      uses: actions/cache@v4
      with:
        path: apps/mobile/fastlane/DerivedData
        key: ${{ runner.os }}-derived-data-xcode-${{ env.XCODE_VERSION }}-${{ hashFiles('apps/mobile/ios/Podfile.lock') }}-${{ hashFiles('apps/mobile/package.json') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-xcode-${{ env.XCODE_VERSION }}-
