name: Validate Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  validateTitle:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Validate commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            perf
            chore
            refactor
            revert
          requireScope: true
          # This pattern ensures the PR title doesn't contain any double quotes
          subjectPattern: ^(?!.*["]).*$
